A = LOAD 'data3' USING PigStorage('\t') AS (a:int, b:int);
B = GROUP A by a;                                         
C = FOREACH B GENERATE $0, $1.$1; 
Register x.py using jython as x;
D = FOREACH C GENERATE x.getPairs($1);
E = FOREACH D GENERATE FLATTEN(STRSPLIT($0, '@')) ;
F = FILTER E BY $0 != '';
G = FOREACH F GENERATE FLATTEN(TOBAG(*));
H = GROUP G BY $0;
I = FOREACH H GENERATE group, COUNT($1);
J = FILTER I BY $1 >= 5;
STORE J INTO 'OUTPUT' USING PigStorage(',');
